@url_dev=http://localhost:3056/v1/api/
### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop TIPS2711",
    "email": "shoptipjs33122@gmail.com",
    "password": "abc123"
}